Fixed several spelling errors under colossalai
hpcaitech/ColossalAI pull request #3618
Opened 2023-04-21 01:21 UTC by digger-yu

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [ ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

Not involved

## 📝 What does this PR do?

Optimization Code
Fixed several spelling errors under colossalai,The code logic is not modified
Note on readme.md file changes
GitHub's image caching mechanism will cache images,Add a random number after the last modified link.
so that every time you visit that link, the contributor's image will be refreshed in real time.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2023-04-21 09:59 UTC, digger-yu commented
> 
sorry,I don't understand too well, what I need to do ?

2023-04-24 04:59 UTC, binmakeswell commented
> > 
> 
> sorry,I don't understand too well, what I need to do ?

Hi @digger-yu Don't worry. You can update these changes according to above comments at digger-yu:main, then we will review it. Thanks.

2023-04-24 10:31 UTC, binmakeswell commented
Hi @digger-yu Thank you for your careful and informative contribution. I have reviewed all the content and think it is pretty nice!
I would suggest you fix the bugs according to the above comments first, and then I can merge this PR.
Because Colossal-AI is in high-speed development, modifying too many files at one time is likely to cause conflicts with other contributors' PRs, causing unnecessary extra work. 
For example, you can split your further PR according to the path, docs/example/colossalai/application/etc. 
Thanks.

2023-04-24 10:45 UTC, digger-yu commented
@binmakeswell 
It's an honor to contribute to the open source world.
I'll go through it all as soon as I can, it's almost done.
Most of the changes are actually words in comments.
The individual changes like Usgae::Usage:: are related to the code logic.
But I think this is just to restore the function of its design.

2023-04-25 06:42 UTC, binmakeswell commented
![image](https://user-images.githubusercontent.com/61670638/234194749-bf37dbb4-0244-4ec2-88bb-4b8eebd108eb.png)

Hi @digger-yu 
Could you please fix bugs according to comments at the beginning of this PR first, rather than adding new changes?  It may only take a few minutes. You've modified almost a hundred files at once, which is a lot for a PR.
Although these changes aren't related to the code logic, unfortunately, some of them are incorrect, and we should fix them before merging this PR.
Thank you very much.

2023-04-25 07:17 UTC, digger-yu commented
@binmakeswell 
Sorry for the trouble you caused
question 1 :Here just add a random number to make sure that each visit is the latest list of images and not cached, it is effective
question 2 :Already revert

2023-04-25 09:13 UTC, binmakeswell requested changes

2023-04-25 09:23 UTC, digger-yu commented on colossalai/autochunk/search_chunk.py
> +    Chunks will be selected one by one utile search stops.
done

2023-04-25 09:26 UTC, digger-yu commented on docs/source/en/features/1D_tensor_parallel.md
> +Let's define a model that consists of a two-layer multi-layer perception (MLP) as below.
revert

2023-04-25 09:30 UTC, digger-yu commented on docs/source/en/features/2D_tensor_parallel.md
> -Let's define a model that consists of a two-layer multi-layer perceptron (MLP) as below.
revert

2023-04-25 09:30 UTC, digger-yu commented on docs/source/en/features/2p5D_tensor_parallel.md
> -Let's define a model that consists of a two-layer multi-layer perceptron (MLP) as below.
revert

2023-04-25 09:33 UTC, digger-yu commented on examples/language/gpt/experiments/auto_parallel/README.md
> +#Run the auto parallel resent example with 4 GPUs with a dummy dataset.
revert

2023-04-25 09:55 UTC, digger-yu commented on colossalai/autochunk/reorder_graph.py
> +    Reorder node list and indices trace list
revert

2023-04-25 09:55 UTC, digger-yu commented on colossalai/auto_parallel/passes/runtime_preparation_pass.py
> -            # loop, so we don't need to track these operations in the autograd graph.
revert

2023-04-25 09:57 UTC, digger-yu commented on colossalai/communication/p2p.py
> -    Adapted from megatron.p2p_communication.
revert

2023-04-25 09:59 UTC, digger-yu commented on colossalai/initialize.py
> -    """A wrapper for colossalai.launch for torchrun or torch.distributed.launch by reading rank and world size
revert

2023-04-25 10:00 UTC, digger-yu commented on colossalai/nn/layer/moe/routers.py
> +    for routing usage. More derailed function can be found in the paper about Switch Transformer
done

2023-04-25 10:01 UTC, digger-yu commented on colossalai/nn/layer/moe/routers.py
> +    for routing usage. More derailed function can be found in the paper about ViT-MoE.
done

2023-04-25 10:03 UTC, digger-yu commented on README.md
> +  <img src="https://contrib.rocks/image?repo=hpcaitech/ColossalAI&r="  width="800px"/>
revert

2023-04-25 10:11 UTC, binmakeswell commented
> @binmakeswell Sorry for the trouble you caused question 1 :it just add a random number to make sure that each visit is the latest list of images and not cached, it is effective question 2 :Already revert

oh, I'm so sorry, I forgot to submit the review comments and you actually cannot read them before. 
Thank you very much for your patience and contribution.

2023-04-25 10:13 UTC, binmakeswell approved these changes

2023-04-26 03:30 UTC, binmakeswell approved these changes

2023-04-26 03:38 UTC, merged