Add Inference test for llama
hpcaitech/ColossalAI pull request #4508
Opened 2023-08-24 08:38 UTC by yuehuayingxueluo

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [ ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2023-08-24 09:47 UTC, CjhHa1 commented on tests/test_infer/llama_infer_eigine.py
> +        print(block_loc.shape)
del `print` here

2023-08-24 09:47 UTC, CjhHa1 commented on tests/test_infer/llama_infer_eigine.py
> +            enable_tensor_parallelism=True,
you can add `inference only` = true

2023-08-24 09:47 UTC, CjhHa1 commented on tests/test_infer/llama_infer_eigine.py
> +        else:
we still need to use infer policy even if cache manager is not needed?

2023-08-25 04:08 UTC, tiandiao123 requested changes

2023-08-30 04:09 UTC, tiandiao123 approved these changes
LGTM！

2023-08-30 04:10 UTC, merged