[Bug Fix] fix rotary embedding in llama
hpcaitech/ColossalAI pull request #4608
Opened 2023-09-04 09:10 UTC by Xu-Kai

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [ ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2023-09-04 09:37 UTC, CjhHa1 commented on tests/test_infer/test_llama_infer.py
> +            print(output_text)
remove useless print in test

2023-09-04 09:37 UTC, CjhHa1 commented on tests/test_infer_ops/triton/test_rotary_embedding.py
> +    print("max delta:", torch.max(torch.abs(y_torch - y_triton)))
remove this

2023-09-05 06:35 UTC, yuanheng-zhao commented on colossalai/inference/tensor_parallel/engine.py
> +                curr_seq_len = len(attn_mask)
This is a temporary fix. In future we might revise it by concatenating input ids into a single tensor and modify model modelling (e.g. embedding in model forward, decoder layer, etc)

2023-09-05 06:43 UTC, yuehuayingxueluo commented on colossalai/inference/tensor_parallel/modeling/llama.py
> +        if infer_state.is_context_stage:
Swap codes between 129~142 lines  and codes between144~152 lines to avoid redundant code, “position_ids = None”

2023-09-05 08:56 UTC, tiandiao123 requested changes

2023-09-05 08:59 UTC, tiandiao123 approved these changes

2023-09-05 08:59 UTC, merged