Rlhf fix bugs. Tested.
hpcaitech/ColossalAI pull request #4860
Opened 2023-10-06 07:05 UTC by YeAnbang

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [ ] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [ ] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2023-10-08 02:13 UTC, TongLi3701 commented
Hi @YeAnbang ,

is this branch ready to review? Could you check the CI and make sure they are all passed.

2023-10-24 07:29 UTC, TongLi3701 commented on applications/Chat/coati/experience_maker/naive.py
> +        with torch.no_grad():
This function has been marked as `torch.no_grad()`

2023-10-24 07:35 UTC, TongLi3701 commented on applications/Chat/coati/trainer/rm.py
> +        self.model.eval()
Why do u change it to `eval` mode?

2023-10-26 05:16 UTC, TongLi3701 requested changes
Thanks Anbang.

Overall looks good. 

However, I do recommend supporting more dataset to consolidate the whole pipeline. For example, https://huggingface.co/datasets/Cohere/miracl-zh-queries-22-12 ， to test the robustness of the pipeline.

Thanks

2023-10-26 05:16 UTC, TongLi3701 commented on applications/Chat/tests/test_experience.py
> +    experience_maker = NaiveExperienceMaker(actor, critic, reward_model, initial_model, tokenizer, tokenizer)
Why do we need 2 tokenizers?

2023-11-01 05:29 UTC, TongLi3701 approved these changes
Thanks Anbang.

Some minor comments.

2023-11-01 05:29 UTC, TongLi3701 commented on applications/Chat/coati/dataset/prompt_dataset.py
> +        print(instructions[:2])
Please use logger

2023-11-01 05:29 UTC, TongLi3701 commented on applications/Chat/coati/dataset/utils.py
> +        return ""
Why do we need two functions for this ?

It seems that we can only use one function.

2023-11-01 06:08 UTC, ver217 commented on LICENSE
> -   of this software and associated documentation files (the "Software"), to deal
Why?

2023-11-01 06:09 UTC, ver217 commented on applications/Chat/coati/dataset/prompt_dataset.py
> +        print(instructions[:2])
Why print the first two instructions? If it's for debugging, please delete it.

2023-11-01 06:11 UTC, ver217 commented on applications/Chat/coati/dataset/reward_dataset.py
> +logger = get_dist_logger()
This should be a local variable. Please avoid using global variable if unnecessary.

2023-11-01 06:13 UTC, ver217 commented on applications/Chat/coati/dataset/reward_dataset.py
> +            logger.info("chosen: ", chosen[:2])
The correctness should be guaranteed by unit tests rather than logging. If it's for debugging, please remove all kinds of codes like this.

2023-11-01 06:16 UTC, ver217 commented on applications/Chat/coati/dataset/utils.py
> +def read_data_by_schema(data, schema: str):
Please add type hint for return value

2023-11-01 06:16 UTC, ver217 commented on applications/Chat/coati/dataset/utils.py
> +def read_data_by_schema(data, schema: str):
And for all arguments

2023-11-01 06:18 UTC, ver217 commented on applications/Chat/coati/dataset/utils.py
> +def read_data_by_schema(data, schema: str):
It seems that this function is only used in `read_string_by_schema`. If so, why not merge these two functions?

2023-11-01 06:19 UTC, ver217 commented on applications/Chat/coati/experience_maker/naive.py
> +        self.critic.train()
This is an inference process. Why call `model.train()`?

2023-11-01 06:20 UTC, ver217 commented on applications/Chat/coati/experience_maker/naive.py
> +        lastgaelam = 0
Extract line 88-98 to a function or method

2023-11-01 06:22 UTC, ver217 commented on applications/Chat/coati/models/loss.py
> +        # advantages = advantages.clamp(-0.7, 0.7)
If these comments are useless, please remove them. Otherwise, please add some explaination.

2023-11-01 06:24 UTC, ver217 commented on applications/Chat/coati/models/utils.py
> +    approx_kl = log_probs_base - log_probs
Which formula do you use? Can you provide a reference here?

2023-11-01 06:26 UTC, ver217 commented on applications/Chat/coati/trainer/base.py
> +                        LORA_MANAGER.merge_weights = True
I think `merge_weights=True` should be set as a default behavior. The merged weights are much larger than lora weights. Most users only want to save lora weights. We can provide a script to merge them offline.

2023-11-01 06:27 UTC, ver217 commented on applications/Chat/coati/trainer/ppo.py
> +        if not to_skip:
Overflow is checked in `optimizer.step()`. You don't need extra check here.

2023-11-01 06:28 UTC, ver217 commented on applications/Chat/coati/trainer/ppo.py
> +                print(response_text[i])
Line 208-211 confuse me. What's the effect of the code?

2023-11-01 06:30 UTC, ver217 commented on applications/Chat/examples/README.md
> +## Get Start with torchrun (ELASTIC LAUNCH)
Colossalai run is much simpler when training with multi-nodes

2023-11-01 06:48 UTC, ver217 commented on applications/Chat/examples/test_logits.py
> +model_name = "/home/lcyab/data/Anthropic_rlhf/actor/pretrain"  # You can use other GPT-2 variants like "gpt2-medium", "gpt2-large", etc.
Do not put local path here.

2023-11-01 06:49 UTC, ver217 commented on applications/Chat/examples/test_logits.py
> +model_name = "/home/lcyab/data/Anthropic_rlhf/actor/pretrain"  # You can use other GPT-2 variants like "gpt2-medium", "gpt2-large", etc.
Should this file be added to tests?

2023-11-01 06:50 UTC, ver217 commented on applications/Chat/examples/train_prompts.py
> +from torch.optim.lr_scheduler import CosineAnnealingLR
The naming of this file is a little confusing. I recomment that we name stage-1 as `train_sft.py` and stage-3 as `train_rlhf.py`. What do you think of this?

2023-11-01 06:54 UTC, ver217 commented on applications/Chat/examples/train_rlhf_sft.py
> +            model = BLOOMActor(pretrained=args.pretrain, lora_rank=args.lora_rank, checkpoint=args.grad_checkpoint)
The concept of `actor` is only meaningful in RLHF stage. We can use the original LM here, and use booster api directly.

2023-11-01 06:55 UTC, ver217 commented on applications/Chat/tests/test_train.sh
> +DATA_DIRECTORY="/data/scratch/github_actions/chat"
Set this path in workflow file through envrionment variable.

2023-11-03 03:05 UTC, ver217 commented on LICENSE
> -   limitations under the License.
DON'T delete

2023-11-03 03:08 UTC, ver217 commented on applications/Chat/coati/experience_maker/naive.py
> +            **{
This is strange. Why not pass kwargs directly? Like `sequences=xxx, attention_mask=xxx`

2023-11-03 03:09 UTC, ver217 commented on applications/Chat/coati/models/loss.py
> +        if masked_mean(ratio_, action_mask).max()>15.0:
Where is `15.0` from?

2023-11-03 03:09 UTC, ver217 commented on applications/Chat/coati/models/loss.py
> +        ratio = ratio_.clamp(0.0, 10.0)
Where is `10.0` from?

2023-11-03 03:11 UTC, ver217 commented on applications/Chat/coati/trainer/base.py
> +                            self.actor_optim, "actor_optim_checkpoint_prompts_%d.pt" % (torch.cuda.current_device()), only_rank0=False
Why not enable only rank0?

2023-11-08 03:43 UTC, ver217 commented on applications/Chat/examples/README.md
> +<img width="1000" alt="image" src="https://raw.githubusercontent.com/YeAnbang/imagehostingrepo/main/mean_reward_chart.png">
Move this to `hpcaitec/public_asstes`

2023-11-08 06:25 UTC, ver217 commented on applications/Chat/coati/experience_maker/naive.py
> +        sequences_rm = self.rm_model_tokenizer(
Please check this. In theory, the critic and reward model have the same initial weights, their tokenizers should be the same.

2023-11-12 06:17 UTC, CZYCW commented on applications/Chat/examples/train_rlhf_sft.py
> +    strategy.save_pretrained(model, path=args.save_path, only_rank0=True, tokenizer=tokenizer)
`only_rank0` is removed in https://github.com/hpcaitech/ColossalAI/commit/be400a09364942a02e0048d940f3699380cd6f1f. You can probably omit this field.

2023-11-24 09:55 UTC, closed without merging