[hotfix]fix chatglm rmsnorm
hpcaitech/ColossalAI pull request #5079
Opened 2023-11-21 04:21 UTC by CjhHa1

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [x] I have added relevant tags if possible for us to better distinguish different PRs

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

This PR fixes the import err of chatglm rmsnorm

## 💥 Checklist before requesting a review

- [ ] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests.
- [ ] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2023-11-21 04:46 UTC, ver217 commented on colossalai/inference/engine/policies/chatglm2.py
> +        return None
This should raise an exception

2023-11-21 05:45 UTC, CjhHa1 commented on colossalai/inference/engine/policies/chatglm2.py
> +        return None
fixed

2023-11-22 09:52 UTC, CjhHa1 commented
before replace rms_norm
![image](https://github.com/hpcaitech/ColossalAI/assets/72591262/b4bfa2ee-7de0-41ac-bb9f-f82dae3660ff)

after rms_norm
![image](https://github.com/hpcaitech/ColossalAI/assets/72591262/75ae733c-d0c1-4458-b0be-33d89c203d4a)

2023-11-22 09:56 UTC, ver217 requested changes

2023-11-22 09:56 UTC, ver217 commented on colossalai/inference/engine/policies/chatglm2.py
> +            if infer_forward is not None:
If `HAS_TRITON_RMSNORM`, the `infer_forward` won't be None

2023-11-22 09:59 UTC, merged