[Chat] Fix lora
hpcaitech/ColossalAI pull request #5946
Opened 2024-07-29 05:53 UTC by YeAnbang

## 📌 Checklist before creating the PR

- [ ] I have created an issue for this PR for traceability
- [x] The title follows the standard format: `[doc/gemini/tensor/...]: A concise description`
- [ ] I have added relevant tags if possible for us to better distinguish different PRs
- [x] I have installed pre-commit: `pip install pre-commit && pre-commit install`

## 🚨 Issue number

> Link this PR to your issue with words like fixed to automatically close the linked issue upon merge
>
> e.g. `fixed #1234`, `closed #1234`, `resolved #1234`

## 📝 What does this PR do?

> Summarize your work here.
> if you have any plots/diagrams/screenshots/tables, please attach them here.

## 💥 Checklist before requesting a review

- [x] I have linked my PR to an issue ([instruction](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
- [ ] My issue clearly describes the problem/feature/proposal, with diagrams/charts/table/code if possible
- [x] I have performed a self-review of my code
- [x] I have added thorough tests.
- [x] I have added docstrings for all the functions/methods I implemented

## ⭐️ Do you enjoy contributing to Colossal-AI?

- [x] 🌝 Yes, I do.
- [ ] 🌚 No, I don't.

Tell us more if you don't enjoy contributing to Colossal-AI.

2024-07-29 11:04 UTC, TongLi3701 requested changes
Thanks Anbang.

Just left some comments. 

Normally we should also support Lora for RLHF methods. Please also add tests or instructions for them. Thanks.

2024-07-29 11:04 UTC, TongLi3701 commented on applications/ColossalChat/tests/test_lora.py
> +    assert torch.allclose(out_linear, out_lora, atol=1e-5)
Normal we should also check `rtol`

2024-07-30 06:44 UTC, YeAnbang commented on applications/ColossalChat/coati/models/lora.py
> +                nn.init.zeros_(self.lora_B)
no need nn.Parameter has require_grad=True by default

2024-07-30 06:50 UTC, YeAnbang commented on applications/ColossalChat/coati/models/lora.py
> +            trainable_parameter_size += p.numel()
The trainable parameter size captures the trainable parameters after converting to lora model, so only lora_A and lora_Bs count.

2024-07-30 06:52 UTC, YeAnbang commented on applications/ColossalChat/coati/models/lora.py
> +        if weight is not None:
removed

2024-07-30 06:52 UTC, YeAnbang commented on applications/ColossalChat/coati/models/lora.py
> +        nn.init.normal_(self.lora_B)
yes

2024-07-31 06:09 UTC, TongLi3701 approved these changes
Thanks Anbang.

2024-07-31 06:10 UTC, merged